version = 2
name = "udp-broadcast-gga"

[[channels]]

[channels.interface]
type = "udp"

[channels.interface.mode]
type = "unicast"
destination = "192.168.1.116:18180"

[[channels.messages]]
interval_ms = 1000

[channels.messages.payload]
type = "nmea"
talker = "GP"
sentence_type = "GGA"
fields = []

[logging]
level = "info"
stdout = true
